# -*- coding: utf-8 -*-
"""DataElevateTask7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxfFuRYBssBwOw34QSPQoLYNbOK1tht2
"""

import sqlite3

# 1. Connect to database (creates file if not exists)
conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

# 2. Create a table
cursor.execute("""
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product TEXT,
    quantity INTEGER,
    price REAL
)
""")

# 3. Insert some dummy sales data
sales_data = [
    ("Laptop", 3, 60000),
    ("Laptop", 2, 62000),
    ("Phone", 5, 20000),
    ("Phone", 3, 22000),
    ("Tablet", 4, 15000),
    ("Tablet", 6, 15500)
]

cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sales_data)

conn.commit()
conn.close()

print("Database created and data inserted successfully!")

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# 1. Connect to database
conn = sqlite3.connect("sales_data.db")

# 2. Run SQL query to summarize data
query = """
SELECT
    product,
    SUM(quantity) AS total_qty,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""
df = pd.read_sql_query(query, conn)

# Close connection
conn.close()

# 3. Display results
print("Sales Summary:\n")
print(df)

# 4. Plot a simple bar chart
df.plot(kind='bar', x='product', y='revenue', legend=False)
plt.title("Revenue by Product")
plt.ylabel("Revenue")
plt.xlabel("Product")
plt.tight_layout()

# Save chart (optional)
plt.savefig("sales_chart.png")
plt.show()